name: kapwa_companion_basic
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1     
  logging: ^1.2.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  provider: ^6.1.5
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.0
  audioplayers: ^6.0.0
  flutter_webrtc: ^0.14.2
  flutter_svg: ^2.0.7
  socket_io_client: ^3.1.2
  shared_preferences: ^2.2.2
  webview_flutter: ^4.9.0
  permission_handler: ^11.0.0
  path_provider: ^2.1.1
  flutter_widget_from_html: ^0.10.0+1
  url_launcher: ^6.2.1  # Added missing dependency

dev_dependencies:
  dwds: ^24.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.4

dependency_overrides:
  js: 0.7.2
  plugin_platform_interface: 2.1.5

flutter:
  uses-material-design: true
  
  # Assets are now loaded conditionally based on environment
  assets:
    - .env
    - assets/images/typing_dots.gif
    - assets/podcast_sources/
    - assets/story_sources/