name: kapwa_companion_basic
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  provider: ^6.1.5
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  firebase_core: ^3.13.0
  firebase_auth: 5.5.3
  cloud_firestore: ^5.6.0
  audioplayers: ^6.0.0
  flutter_webrtc: ^0.12.1
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  js: 0.7.2

flutter:
  uses-material-design: true
  
  # Assets are now loaded conditionally based on environment
  assets:
    - .env
    - assets/audio_sources/