services:
  - type: web
    name: ofw-admin-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: CHROMA_DB_PATH
        value: /opt/render/project/src/kapwa_companion/chroma_db
      - key: OPENAI_API_KEY
        sync: false

