// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw0wkBUglPXZLPxN6jCwbpt6jhh7PXpQQ',
    appId: '1:755824912207:web:8143b76ae35aa219a8473a',
    messagingSenderId: '755824912207',
    projectId: 'kapwa-companion-basic',
    authDomain: 'kapwa-companion-basic.firebaseapp.com',
    storageBucket: 'kapwa-companion-basic.firebasestorage.app',
    measurementId: 'G-77MX06585H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcZuAsRRpNrNopWlLZY6-HKfa9B-F5LqU',
    appId: '1:755824912207:android:193b7c8288490ca4a8473a',
    messagingSenderId: '755824912207',
    projectId: 'kapwa-companion-basic',
    storageBucket: 'kapwa-companion-basic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByV0qWpv7WLBLU7_ILuYtALbbqqn6NaSs',
    appId: '1:755824912207:ios:ed0aebd40bfb7f54a8473a',
    messagingSenderId: '755824912207',
    projectId: 'kapwa-companion-basic',
    storageBucket: 'kapwa-companion-basic.firebasestorage.app',
    iosBundleId: 'com.example.kapwaCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByV0qWpv7WLBLU7_ILuYtALbbqqn6NaSs',
    appId: '1:755824912207:ios:ed0aebd40bfb7f54a8473a',
    messagingSenderId: '755824912207',
    projectId: 'kapwa-companion-basic',
    storageBucket: 'kapwa-companion-basic.firebasestorage.app',
    iosBundleId: 'com.example.kapwaCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw0wkBUglPXZLPxN6jCwbpt6jhh7PXpQQ',
    appId: '1:755824912207:web:9b4bc0f1dd6e1336a8473a',
    messagingSenderId: '755824912207',
    projectId: 'kapwa-companion-basic',
    authDomain: 'kapwa-companion-basic.firebaseapp.com',
    storageBucket: 'kapwa-companion-basic.firebasestorage.app',
    measurementId: 'G-QNT8Q4B16K',
  );

}