// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4NPZ22YVWlL4o_3zhOjHI5sOlJsoSZlQ',
    appId: '1:980700289813:web:6ff0832e4f586da0ff271c',
    messagingSenderId: '980700289813',
    projectId: 'kapwa-companion',
    authDomain: 'kapwa-companion.firebaseapp.com',
    storageBucket: 'kapwa-companion.firebasestorage.app',
    measurementId: 'G-D92058XXH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg9DpVLhhsA9Ej5fNpn6lhH_UJXxwCr1s',
    appId: '1:980700289813:android:727a37b09c61ea69ff271c',
    messagingSenderId: '980700289813',
    projectId: 'kapwa-companion',
    storageBucket: 'kapwa-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB69a-l4wqwnbf0P-zORzGUlYF7CKoZrZQ',
    appId: '1:980700289813:ios:27f3b76c690a70d4ff271c',
    messagingSenderId: '980700289813',
    projectId: 'kapwa-companion',
    storageBucket: 'kapwa-companion.firebasestorage.app',
    iosBundleId: 'com.example.kapwaCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB69a-l4wqwnbf0P-zORzGUlYF7CKoZrZQ',
    appId: '1:980700289813:ios:27f3b76c690a70d4ff271c',
    messagingSenderId: '980700289813',
    projectId: 'kapwa-companion',
    storageBucket: 'kapwa-companion.firebasestorage.app',
    iosBundleId: 'com.example.kapwaCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4NPZ22YVWlL4o_3zhOjHI5sOlJsoSZlQ',
    appId: '1:980700289813:web:3f95d7c01eaa57ecff271c',
    messagingSenderId: '980700289813',
    projectId: 'kapwa-companion',
    authDomain: 'kapwa-companion.firebaseapp.com',
    storageBucket: 'kapwa-companion.firebasestorage.app',
    measurementId: 'G-8CL386N87J',
  );
}
